routes/playlists.py
from flask import Blueprint, render_template, redirect, url_for, request, current_app, session
from main import db, download_video
from scripts import email_to_id
from youtube_search import YoutubeSearch
from spotify import get_all_song_names
from proxy import get_proxy
import os, json, time
from scripts import *
import requests
from threadedreturn import ThreadWithReturnValue
import asyncio
import aiohttp
from concurrent.futures import ThreadPoolExecutor

playlists_bp = Blueprint('playlists', __name__)

def divide_into_groups(lst, group_size):
    return [lst[i:i + group_size] for i in range(0, len(lst), group_size)]



@playlists_bp.route("/playlist-create", methods=["GET", "POST"])
def create_playlist():
    if session['email'] is None:
        return redirect(url_for('login'))
    if request.method == "POST":
        name = request.form.get("name")
        with current_app.app_context():
            owner_id = email_to_id(session['email'])
            if owner_id is not None:
                db.execute("INSERT INTO playlists (owner_id, name) VALUES (?, ?)", (owner_id[0], name))
    return redirect(url_for('playlists.playlist'))

@playlists_bp.route("/playlists")
def playlist():
    if 'email' not in session:
        return redirect(url_for('auth.login'))
    user_id = email_to_id(session['email'])
    if user_id is None:
        return redirect(url_for('auth.register'))
    playlists_json = []
    playlists = db.execute("SELECT * FROM playlists WHERE owner_id = ?", (user_id[0],)).fetchall()
    for playlist in playlists:
        playlists_json.append({"id": playlist[0], "owner_id": playlist[1], "songs":playlist[2], "name": playlist[3]})
    return render_template('playlists.html', playlists=playlists_json)

@playlists_bp.route("/add_song", methods=["POST"])
def add_song():

    song_id = request.form["song_id"]
    pl_id = request.form["pl_id"]
    res = db.execute("SELECT * from playlists where owner_id = ? AND id = ?", (email_to_id(session['email'])[0], pl_id)).fetchone()
    if res is not None:
        old_songs = res[2]
        if old_songs is None:
            old_songs = ""
        new_songs = f"{old_songs}&&{song_id}"
        db.execute("UPDATE playlists SET songs = ? WHERE id = ?", (new_songs, pl_id))
        return "Success"
    
    
@playlists_bp.route("/remove_song", methods=["POST"])
def remove_song():

    song_id = request.form["song_id"]
    pl_id = request.form["pl_id"]
    res = db.execute("SELECT * from playlists where owner_id = ? AND id = ?", (email_to_id(session['email'])[0], pl_id)).fetchone()
    if res is not None:
        old_songs = res[2]
        if old_songs is None:
            old_songs = ""
        old_songs_list = old_songs.split("&&")
        print(old_songs_list, song_id)
        old_songs_list.remove(song_id)
        
        new_songs = '&&'.join(old_songs_list)
        db.execute("UPDATE playlists SET songs = ? WHERE id = ?", (new_songs, pl_id))
        return "Success"
    else:
        return "ur not owner"
        
        
@playlists_bp.route("/playlist/<pl_id>", methods=["GET"])
async def play_playlist(pl_id: str):
    request_time = time.time()
    print(time.time() - request_time, 1)
    res = db.execute("SELECT * from playlists where id = ?", (pl_id,)).fetchone()
    print(time.time() - request_time, 2)
    if res is None:
        return "This playlist doesnt exist"
    try:
        songs_list: list=res[2].split("&&")
        songs_list.remove("")
    except:
        songs_list = []
        
    if songs_list == []:
        return render_template('playlist.html', results=None)
    print(time.time() - request_time, 3)

    cleaned_results = await fetch_all_song_info(songs_list)
    owner_name = db.execute("SELECT display_name from users where id = ?", (res[1],)).fetchone()
    return render_template('playlist.html', results=cleaned_results, name=res[3], owner=owner_name[0], pl_id=pl_id)
    

@playlists_bp.route("/spotify", methods=["GET", "POST"])
def spotify():
    pl_id = request.args["pl_id"]
    page = request.args.get("page", 0)
    print(pl_id)
    if 'email' not in session:
        return redirect(url_for('auth.login'))
    clean_returned = []
    songs = get_all_song_names(pl_id)
    grouped_songs = divide_into_groups(songs, 10)

    def process_song(song):

        try:
            results_json = YoutubeSearch(song, max_results=1).to_dict()
            if results_json:
                result = results_json[0]
                print(result, 1.5)
                ThreadWithReturnValue(target=download_video, args=(result["id"],)).start()
                try:
                    clean_returned.append(
                        {
                            "id": result["id"],
                            "title": result["title"],
                            "channel": result["channel"],
                            "thumbnail": result["thumbnails"][0],
                        }
                    )
                except IndexError:
                    print(result)
            else:
                print("No results found for:", song)
        except Exception as e:
            print(e, 1)

    print(songs, page)
    with ThreadPoolExecutor(max_workers=4) as executor:
        
        executor.map(process_song, grouped_songs[int(page)])

    playlists = get_playlists(session['email'])
    return render_template("search.html", results=clean_returned, playlists=playlists)

routes/search.py
from flask import Blueprint, render_template, request, current_app, session, redirect, url_for
from main import download_video

import random, requests
from youtube_search_music import YoutubeMusicSearch
from threadedreturn import ThreadWithReturnValue
from config import GOOGLE_API
from main import db
from scripts import get_playlists

from threadedreturn import ThreadWithReturnValue
search_bp = Blueprint('search', __name__)

@search_bp.route("/", methods=["GET"])
def index():
    return render_template("index.html")


@search_bp.route("/search", methods=["POST", "GET"])
def search():
    if 'email' not in session:
        return redirect(url_for('auth.login'))
    if request.method == "POST":
        query = request.form["search_query"]
        results_json = YoutubeMusicSearch(GOOGLE_API).search(query)

        print(results_json)
        threads = {}
        i = 0
        cleaned_results = list(results_json["items"])
        for result in cleaned_results:
            threads[i] = ThreadWithReturnValue(
                target=download_video, args=(result["id"]["videoId"],)
            )
            threads[i].start()
            i += 1
        for i2 in range(len(threads)):
            status = threads[i2].join()
            if status == "Blacklisted":
                cleaned_results.remove(results_json["items"][i2])

            print(status)

        clean_returned = []
        for result in cleaned_results:
            snippet = result["snippet"]

            try:
                clean_returned.append(
                    {
                        "id": result["id"]["videoId"],
                        "title": snippet["title"],
                        "channel": snippet["channelTitle"],
                        "thumbnail": snippet["thumbnails"]["default"]["url"],
                    }
                )
            except IndexError:
                print(result)
        playlists = get_playlists(session['email'])
        print(clean_returned)
        return render_template("search.html", results=clean_returned, playlists=playlists)
    else:
        return render_template("search.html", results=None)
    
@search_bp.route("/home", methods=["GET"])
async def home():
    print(1)
    songs_list = requests.get("https://musicbackend.lunes.host/list_songs", timeout=60).json()
    songs_info = random.choices(songs_list, k=100)
    if 'email' in session:
        playlists = get_playlists(session['email'])
    else:
        playlists = None

    return render_template('home.html', results=songs_info, playlists=playlists)
    

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="Wavify">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Wavify">
    <meta property="og:description" content="Explore ad-free music with Wavify">
    <meta name="description" content="Explore ad-free music with Wavify">
    <meta name="og:url" content="https://music.lunes.host">
    <meta name="theme-color" content="#fbcf59">
    <meta property="og:image:width" content="627">
    <meta property="og:image:height" content="627">
    <!-- <link type="application/json+oembed" href="https://paste.chriz.cf/raw/unopakivuh"> -->
    <meta name="keywords" content="music wavify lunes">
    <meta name="author" content="Wavify">
    <title>Search Page</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        header {
            background-color: #333;
            color: white;
            padding: 1em;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        .result {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            background-color: #fff;
        }

        .result img {
            max-width: 100%;
            height: auto;
            border-radius: 3px;
        }

        h2 {
            color: #333;
        }

        p {
            color: #777;
        }

        #audioPlayerContainer {
                position: sticky;
                bottom: 0;
                background-color: white;
                padding: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                border-radius: 5px;
        }
        a {
            color: #92ffc4;
        }
            

    </style>
    <script src="{{ url_for('static', filename='search.js') }}"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6122367965027230"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-f9+4c+9l-cm-3i"
     data-ad-client="ca-pub-6122367965027230"
     data-ad-slot="7394356391"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var addSongButtons = document.querySelectorAll('.add-song-button');
    
            addSongButtons.forEach(function(button) {
                button.addEventListener('click', function() {
                    var songId = this.getAttribute('data-song-id');
                    var playlistId = document.getElementById('playlist_to_add').value;
    
                    // Send AJAX request
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', '/add_song', true);
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.onreadystatechange = function() {
                        if (xhr.readyState === 4 && xhr.status === 200) {
                            // Handle the response if needed
                            console.log(xhr.responseText);
                        }
                    };
    
                    // Construct the request body
                    var params = 'song_id=' + encodeURIComponent(songId) + '&pl_id=' + encodeURIComponent(playlistId);
    
                    // Send the request
                    xhr.send(params);
                });
            });
        });
    </script>
    

</head>
<body>
    {% if results is none %}
        <form action="/search" method="post">
            <label for="search_query">Search:</label>
            <input type="text" id="search_query" name="search_query" required>
            <button type="submit">Search</button>
        </form>
    {% else %}
    <form action="/search" method="post">
        <label for="search_query">Search:</label>
        <input type="text" id="search_query" name="search_query" required>
        <button type="submit">Search</button>
    </form>
        <header>
            <h1>Explore songs</h1>
            <a href= "{{ url_for('playlists.playlist')}}">Playlists</a>
        </header>
        <main>
            {% if playlists is not none %}
            <select id="playlist_to_add" name="playlist_to_ad" required>
                
                {% for playlist in playlists %}
                <option value="{{ playlist[0] }}">{{ playlist[3] }}</option>
                {% endfor %}
            </select>
            {%endif%}

            {% for result in results %}
            <div class="result" id="result" onClick="almostPlaySong('{{ result.yt_id }}', '{{ result.title }}')">

                <img src="https://i.ytimg.com/vi/{{ result.yt_id }}/default.jpg" alt="{{ result.title }}">
                <h2>{{ result.title }}</h2>
                <p><strong>Channel:</strong> {{ result.channel }}</p>
                <button class="add-song-button" data-song-id="{{ result.id }}">Add to Playlist</button>


                
            </div> 
            {% endfor %}

            
        </main>
        <div id="audioPlayerContainer"></div>
    {% endif %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Page</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.4.17/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6122367965027230"
     crossorigin="anonymous"></script>
    <!-- Ads baby -->
    <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-6122367965027230"
        data-ad-slot="8775962733"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</head>

<body data-theme="night">
    <div class="hero min-h-screen bg-base-200">
        <div class="hero-content text-center">
            <div class="max-w-md">
                <h1 class="text-5xl font-bold">Waveify</h1>
                <p class="py-6">Where music should not and should never be behind a paywall.</p>
                <a href={{url_for('search.home')}}><button class="btn btn-primary">Get Started</button></a>
            </div>
        </div>
    </div>

    <!-- About Section -->
    <div class="bg-base-200 p-8">
        <div class="max-w-2xl mx-auto">
            <h2 class="text-3xl font-bold mb-4">About Waveify</h2>
            <p class="text-lg">Welcome to "Waveify", a place where we provide music without a paywall! Here at Waveify, we believe that music should not be locked behind paywalls or disturbed by ads. With Waveify, you can enjoy your favorite music without annoying ads lurking on your player.</p>
        </div>
    </div>

    <!-- Features Section -->
    <div class="bg-base-200 p-8">
        <div class="max-w-2xl mx-auto">
            <h2 class="text-3xl font-bold mb-4">Features</h2>
            <p class="text-lg">Waveify offers a wide range of features to enhance your music experience. Here are some of the features that we offer:</p>
    
            <br>
    
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div class="bg-base-100 p-4 rounded-lg shadow-md flex items-center">
                    <div>
                        <i class="fas fa-music text-2xl mr-2"></i>
                        <h3 class="text-xl font-bold mb-2">Ad-Free Experience</h3>
                        <p>Enjoy an uninterrupted music experience without any ads.</p>
                    </div>
                </div>
    
                <div class="bg-base-100 p-4 rounded-lg shadow-md flex items-center">
                    <div>
                        <i class="fas fa-headphones text-2xl mr-2"></i>
                        <h3 class="text-xl font-bold mb-2">High-Quality Streaming</h3>
                        <p>Stream your favorite music in high-quality audio.</p>
                    </div>
                </div>
    
                <div class="bg-base-100 p-4 rounded-lg shadow-md flex items-center">
                    <div>
                        <i class="fas fa-globe text-2xl mr-2"></i>
                        <h3 class="text-xl font-bold mb-2">Free Unlimited Access</h3>
                        <p>Access a vast library of songs without any restrictions.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer footer-center p-4 bg-base-200 text-base-content mt-0" style="margin-top: 0;">
        <aside>
          <p>Copyright © 2023 - All right reserved by Waveify Development Team</p>
        </aside>
    </footer>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form id="loginForm" action="{{ url_for('auth.login') }}" method="POST">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" required>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Login</button>
    </form>

    <p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here</a>.</p>
</body>
</html>

templates/playlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{name}}</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="{{name}}">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Wavify">
    <meta property="og:description" content="Playlist {{name}} made by {{owner}}">
    <meta name="description" content="Playlist {{name}} made by {{owner}}">
    <meta name="og:url" content="https://music.lunes.host">
    <meta name="theme-color" content="#fbcf59">
    <meta property="og:image:width" content="627">
    <meta property="og:image:height" content="627">
    <!-- <link type="application/json+oembed" href="https://paste.chriz.cf/raw/unopakivuh"> -->
    <meta name="keywords" content="music wavify lunes">
    <meta name="author" content="Wavify">


    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        header {
            background-color: #333;
            color: white;
            padding: 1em;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        .result {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            background-color: #fff;
        }

        .result img {
            max-width: 100%;
            height: auto;
            border-radius: 3px;
        }

        h2 {
            color: #333;
        }

        p {
            color: #777;
        }

        #audioPlayerContainer {
                position: sticky;
                bottom: 0;
                background-color: white;
                padding: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                border-radius: 5px;
        }
            

    </style>
    <script src="{{ url_for('static', filename='playlist.js') }}"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6122367965027230"
     crossorigin="anonymous"></script>
    <!-- Ads baby -->
    <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-6122367965027230"
        data-ad-slot="8775962733"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var results = {{ results | tojson }};
            results.forEach(function(result) {
                console.log("loop 1");
                almostPlaySong(result.yt_id, result.title);
            });
        });
    </script>


    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var addSongButtons = document.querySelectorAll('.add-song-button');
    
            addSongButtons.forEach(function(button) {
                button.addEventListener('click', function() {
                    var songId = this.getAttribute('data-song-id');
                    var playlistId = {{pl_id}};
    
                    // Send AJAX request
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', '/remove_song', true);
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.onreadystatechange = function() {
                        if (xhr.readyState === 4 && xhr.status === 200) {
                            // Handle the response if needed
                            console.log(xhr.responseText);
                        }
                    };
    
                    // Construct the request body
                    var params = 'song_id=' + encodeURIComponent(songId) + '&pl_id=' + encodeURIComponent(playlistId);
    
                    // Send the request
                    xhr.send(params);
                });
            });
        });
    </script>




</head>
<body>
    {% if results is none %}
        <h1>No songs in this playlist</h1>
    {% else %}
        <header>
            <h1>{{name}} made by {{owner}}</h1>
        </header>
        <main>
            <button class="loop-button" onclick="toggleLoop()">Enable Loop</button>
            {% for result in results %}
            <div class="result" id="result" onClick="almostPlaySong('{{ result.yt_id }}', '{{ result.title }}')">
                <img src="{{ result.thumbnail }}" alt="{{ result.title }}">
                <h2>{{ result.title }}</h2>
                <p><strong>Channel:</strong> {{ result.channel }}</p>
                <button class="add-song-button" data-song-id="{{ result.yt_id }}">Remove from Playlist</button>

                
            </div> 
            {% endfor %}

            
        </main>
        <div id="audioPlayerContainer"></div>
    {% endif %}
</body>
</html>

templates/playlists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Playlists</title>
</head>
<body>
    <h2>playlists</h2>
    <form id="loginForm" action="{{ url_for('playlists.create_playlist') }}" method="POST">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required>
        <button type="submit">Create</button>
    </form>
    <ul>
    {%for playlist in playlists%}
        <li><a href="{{url_for('playlists.play_playlist', pl_id=playlist.id)}}"> {{playlist.name}} </a></li>
    {%endfor%}
    </ul>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
</head>
<body>
    <h2>Register</h2>
    <form id="registerForm" action="{{ url_for('auth.register') }}" method="POST">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>

        <label for="email">Email:</label>
        <input type="text" id="email" name="email" required>

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Register</button>
    </form>

    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login here</a>.</p>
</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Page</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        header {
            background-color: #333;
            color: white;
            padding: 1em;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        .result {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            background-color: #fff;
        }

        .result img {
            max-width: 100%;
            height: auto;
            border-radius: 3px;
        }

        h2 {
            color: #333;
        }

        p {
            color: #777;
        }

        #audioPlayerContainer {
                position: sticky;
                bottom: 0;
                background-color: white;
                padding: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                border-radius: 5px;
        }
            

    </style>
    <script src="{{ url_for('static', filename='search.js') }}"></script>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6122367965027230"
     crossorigin="anonymous"></script>
    <!-- Ads baby -->
    <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-6122367965027230"
        data-ad-slot="8775962733"
        data-ad-format="auto"
        data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var addSongButtons = document.querySelectorAll('.add-song-button');
    
            addSongButtons.forEach(function(button) {
                button.addEventListener('click', function() {
                    var songId = this.getAttribute('data-song-id');
                    var playlistId = document.getElementById('playlist_to_add').value;
    
                    // Send AJAX request
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', '/add_song', true);
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.onreadystatechange = function() {
                        if (xhr.readyState === 4 && xhr.status === 200) {
                            // Handle the response if needed
                            console.log(xhr.responseText);
                        }
                    };
    
                    // Construct the request body
                    var params = 'song_id=' + encodeURIComponent(songId) + '&pl_id=' + encodeURIComponent(playlistId);
    
                    // Send the request
                    xhr.send(params);
                });
            });
        });
    </script>
    

</head>
<body>
    {% if results is none %}
        <form action="/search" method="post">
            <label for="search_query">Search:</label>
            <input type="text" id="search_query" name="search_query" required>
            <button type="submit">Search</button>
        </form>
    {% else %}
    <form action="/search" method="post">
        <label for="search_query">Search:</label>
        <input type="text" id="search_query" name="search_query" required>
        <button type="submit">Search</button>
    </form>
        <header>
            <h1>Search Results</h1>
        </header>
        <main>
            <select id="playlist_to_add" name="playlist_to_ad" required>
                {% for playlist in playlists %}
                <option value="{{ playlist[0] }}">{{ playlist[3] }}</option>
                {% endfor %}
            </select>
            

            {% for result in results %}
            <div class="result" id="result" onClick="almostPlaySong('{{ result.id }}', '{{ result.title }}')">

                <img src="{{ result.thumbnail }}" alt="{{ result.title }}">
                <h2>{{ result.title }}</h2>
                <p><strong>Channel:</strong> {{ result.channel }}</p>
                <button class="add-song-button" data-song-id="{{ result.id }}">Add to Playlist</button>


                
            </div> 
            {% endfor %}

            
        </main>
        <div id="audioPlayerContainer"></div>
    {% endif %}
</body>
</html>